---
- name: Update configuration file conditionally
  hosts: "{{ my_hosts }}"
  become: yes
  vars_files:
    - hosts_vars.yml

  tasks:
    - name: Update role with in file if it exactly matches 'role=my_role'
      ansible.builtin.lineinfile:
        path: /etc/myfile.txt
        regexp: '^role=my_role$'
        line: 'role=a_new_role'
        backrefs: yes
        
