---
- name: Manage service and file cleanup
  hosts: "{{ my_dynamic_hosts }}"
  become: yes
  vars_files:
    - hosts_vars.yml
  tasks:
    - name: Stop the service
      ansible.builtin.systemd:
        name: your_service_name
        state: stopped
    - name: Delete a list of files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /path/to/your/first/file
        - /path/to/your/second/file
        - /path/to/your/third/file
      ignore_errors: yes
    - name: Start the service
      ansible.builtin.systemd:
        name: your_service_name
        state: started
